framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://redis:6379'

        pools:
            app.rate_limiter.storage:
                adapter: cache.adapter.redis
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
