# Configuration Cloudinary
parameters:
    cloudinary.cloud_name: '%env(CLOUDINARY_CLOUD_NAME)%'
    cloudinary.api_key: '%env(CLOUDINARY_API_KEY)%'
    cloudinary.api_secret: '%env(CLOUDINARY_API_SECRET)%'