monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - promo_code
        - payment
        - order
        - mailer
        - cart
        - registration
        - contact
        - media
    

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            promo:
                type: stream
                path: "%kernel.logs_dir%/promo_code.log"
                level: debug
                channels: [promo_code]
            
            # Logs spécifiques pour les paiements
            payment:
                type: stream
                path: "%kernel.logs_dir%/payment.log"
                level: debug
                channels: [payment]
            
            # Logs spécifiques pour les commandes
            order:
                type: stream
                path: "%kernel.logs_dir%/order.log"
                level: debug
                channels: [order]
            
            # Logs spécifiques pour les emails
            mailer:
                type: stream
                path: "%kernel.logs_dir%/mailer.log"
                level: info
                channels: [mailer]
            
            registration:
                type: stream
                path: "%kernel.logs_dir%/registration.log"
                level: debug
                channels: [registration]
            
            contact:
                type: stream
                path: "%kernel.logs_dir%/contact.log"
                level: debug
                channels: [contact]


            media:
                type: stream
                path: "%kernel.logs_dir%/media.log"
                level: info
                channels: ["media"]
            
            # Console output (affiche dans le terminal)
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            
            

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation"]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
             # Logs des erreurs dans un fichier séparé
            error:
                type: stream
                path: "%kernel.logs_dir%/error.log"
                level: error
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
