framework:
  rate_limiter:
    login_limiter:
      policy: fixed_window
      limit: 10
      interval: '1 minute'
      storage_service: app.rate_limiter.storage
    resend_confirmation_limiter:
      policy: fixed_window
      limit: 5
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
    registration_limiter:
      policy: fixed_window
      limit: 5
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
    password_reset_limiter:
      policy: fixed_window
      limit: 5
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
    retractation_limiter:
      policy: fixed_window
      limit: 5
      interval: '1 hour'
      storage_service: app.rate_limiter.storage
    consent_limiter:
      policy: fixed_window
      limit: 30
      interval: '1 hour'
      storage_service: app.rate_limiter.storage
    newsletter_limiter:
      policy: fixed_window
      limit: 5
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
    search_limiter:
      policy: fixed_window
      limit: 30
      interval: '1 minute'
      storage_service: app.rate_limiter.storage
    contact_limiter:
      policy: fixed_window
      limit: 3
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
    review_limiter:
      policy: fixed_window
      limit: 5
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
    checkout_limiter:
      policy: fixed_window
      limit: 10
      interval: '15 minutes'
      storage_service: app.rate_limiter.storage
