# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.frontend_url: '%env(string:FRONTEND_BASE_URL)%'
    app.mailer_from: '%env(string:MAILER_FROM_EMAIL)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # Injection automatique pour tous les services
            $frontBaseUrl: '%app.frontend_url%'
            $fromEmail: '%app.mailer_from%'
            $backendUrl: '%env(BACKEND_BASE_URL)%'
            $projectDir: '%kernel.project_dir%'
            $tempDir: '%kernel.project_dir%/var/documents'
            # Rate limiters
            $loginLimiter: '@limiter.login_limiter'
            $registrationLimiter: '@limiter.registration_limiter'
            $passwordResetLimiter: '@limiter.password_reset_limiter'
            $consentLimiter: '@limiter.consent_limiter'
            $retractationLimiter: '@limiter.retractation_limiter'
            $searchLimiter: '@limiter.search_limiter'
            $resendConfirmationLimiter: '@limiter.resend_confirmation_limiter'
            $newsletterLimiter: '@limiter.newsletter_limiter'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Payment\EventSubscriber\PaymentStatusSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
    App\User\State\UserPasswordHasher:
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
        arguments:
            $logger: '@monolog.logger.registration'
    
    App\Payment\Provider\StripePaymentProvider:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            $logger: '@monolog.logger.payment'
       
    App\Payment\Provider\PaymentProviderFactory:
        arguments:
            $providers: !tagged_iterator { tag: 'app.payment_provider', index_by: 'alias' }
    
    App\Payment\Controller\StripeWebhookController:
        arguments:
            $webhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
            $logger: '@monolog.logger.payment'
    
    App\Shared\Service\MailerService:
        arguments:
            $fromEmail: '%env(MAILER_FROM_EMAIL)%'
            $frontBaseUrl: '%env(FRONTEND_BASE_URL)%'
            $logger: '@monolog.logger.mailer'
            $backendUrl: '%env(BACKEND_BASE_URL)%'

     # Logger personnalisé pour les codes promo
    App\Marketing\Service\PromoCodeService:
        arguments:
            $logger: '@monolog.logger.promo_code'
    
    App\Marketing\Service\PromoCodeApplicationService:
        arguments:
            $logger: '@monolog.logger.promo_code'

    # Logger personnalisé pour les commandes
    App\Payment\Controller\CheckoutController:
        arguments:
            $logger: '@monolog.logger.order'

        
    
    Twig\Extra\Intl\IntlExtension: ~

    App\Shipping\Service\LabelGenerator\LabelGeneratorFactory:
        arguments:
            $generators: !tagged_iterator app.label_generator

    App\Shipping\Service\LabelGenerator\ColissimoLabelGenerator:
        tags: ['app.label_generator']

    App\Shipping\Service\OrderDocumentPdfService:
        arguments:
            $outputDir: '%kernel.project_dir%/var/documents'

    App\Shipping\Service\MapboxGeocodingService:
        arguments:
            $accessToken: '%env(MAPBOX_TOKEN)%'

    App\Shipping\Service\AddressCacheService:
        arguments:
            $cache: '@cache.app'

    App\Shared\Service\MailchimpService:
        arguments:
            $envApiKey: '%env(MAILCHIMP_API_KEY)%'
            $envListId: '%env(MAILCHIMP_LIST_ID)%'
            $envServerPrefix: '%env(MAILCHIMP_SERVER_PREFIX)%'

    app.rate_limiter.storage:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            - '@cache.app'

    App\Media\Service\CloudinaryService:
        arguments:
            $cloudName: '%cloudinary.cloud_name%'
            $apiKey: '%cloudinary.api_key%'
            $apiSecret: '%cloudinary.api_secret%'
    
    App\Media\Command\TestCloudinaryConnectionCommand:
        arguments:
            $cloudName: '%cloudinary.cloud_name%'
            $apiKey: '%cloudinary.api_key%'

    App\Blog\State\BlogPostProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $entityManager: '@doctrine.orm.entity_manager'
            $security: '@security.helper'
            $slugger: '@slugger'
    
    App\Shared\EventListener\LocaleListener:
        arguments:
            $defaultLocale: '%kernel.default_locale%'
            $logger: '@monolog.logger.mailer'
        tags:
            - { name: kernel.event_subscriber }
    
    App\Catalog\State\ProductDeleteProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\Catalog\State\ProductProvider:
        arguments:
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\Catalog\State\ManualTranslationProvider:
        decorates: 'api_platform.doctrine.orm.state.item_provider'
        arguments:
            $decorated: '@.inner'
            $requestStack: '@request_stack'
            $entityManager: '@doctrine.orm.entity_manager'

    # Provider pour les collections
    App\Catalog\State\ManualTranslationCollectionProvider:
        decorates: 'api_platform.doctrine.orm.state.collection_provider'
        arguments:
            $decorated: '@.inner'
            $requestStack: '@request_stack'
            $entityManager: '@doctrine.orm.entity_manager'
    
    App\Contact\State\ContactMessageProcessor:
        arguments:
         $logger: '@monolog.logger.contact'

    App\Catalog\State\ProductPriceProvider:
        decorates: 'api_platform.doctrine.orm.state.item_provider'
        arguments:
            $decorated: '@.inner'
            $requestStack: '@request_stack'

    # Provider pour collections (GET /api/products)
    product_price_collection_provider:
        class: App\Catalog\State\ProductPriceProvider
        decorates: 'api_platform.doctrine.orm.state.collection_provider'
        arguments:
            $decorated: '@.inner'
            $requestStack: '@request_stack'

    App\Media\Service\MediaService:
        arguments:
            $logger: '@monolog.logger.media'

    App\Shipping\Service\ColissimoApiService:
        arguments:
            $apiUrl: '%env(COLISSIMO_API_URL)%'
            $apiKey: '%env(COLISSIMO_API_KEY)%'
            $senderInfo:
                company: '%env(COLISSIMO_SENDER_COMPANY)%'
                firstname: '%env(COLISSIMO_SENDER_FIRSTNAME)%'
                lastname: '%env(COLISSIMO_SENDER_LASTNAME)%'
                address: '%env(COLISSIMO_SENDER_ADDRESS)%'
                zipcode: '%env(COLISSIMO_SENDER_ZIPCODE)%'
                city: '%env(COLISSIMO_SENDER_CITY)%'
                country: '%env(COLISSIMO_SENDER_COUNTRY)%'
                email: '%env(COLISSIMO_SENDER_EMAIL)%'
                phone: '%env(COLISSIMO_SENDER_PHONE)%'
            $productCodes:
                fr: '%env(COLISSIMO_PRODUCT_CODE_FR)%'
                om: '%env(COLISSIMO_PRODUCT_CODE_OM)%'
                eu: '%env(COLISSIMO_PRODUCT_CODE_EU)%'
                eu_out: '%env(COLISSIMO_PRODUCT_CODE_EU_OUT)%'
                intl: '%env(COLISSIMO_PRODUCT_CODE_INTL)%'